steps:
  - label: smith.rs
    plugins:
      - docker#v1.1.1:
          image: smithsecuritydev/ci.rust-1.35:latest
    command:
      - './bin/ci'

  - wait

  - label: smith-cli-docker
    branches: master
    plugins:
      - docker#v1.1.1:
          image: smithsecuritydev/ci.rust-1.35:latest
          environment:
            - "BUILDKITE_BRANCH"
            - "BUILDKITE_BUILD_NUMBER"
      - artifacts#v1.2.0:
          upload: "publish/*"
    command:
      - './bin/publish'

  - wait

  - label: smith-cli-docker
    branches: master
    command:
      - './bin/push'
