[package]
name = "mock-server"
version = "0.1.0"
authors = ["Mark Hibberd <mark@hibberd.id.au>"]
edition = "2018"

[dependencies]
rocket = "0.4.2"
rocket_contrib = "0.4.2"
serde = "1.0.94"
serde_derive = "1.0.94"
serde_json = "1.0.39"
